name: skeleton_keychain
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - pip
  - pip:
      - argschema
      - neuron_morphology
      - skeleton_keys
      - morph_utils
      - .  # install skeleton_keychain itself
